### ISSUE TITLE
Image დირექტორიის დაბილდვა css დირექტორიაში

### ISSUE THREAD

**Issue by IliaNoz** [Girchi/girchi-com-d8#104]
### კონტექსტი
ეხლა Image დირექტორია dist-შია, გვჭირდება რომ სკრიპტმა გაბილდოს dist/css-ში

**Comment by ABGEO07** [comment]
ეს პრობლემა მოგვარებულია ფრონტის დონეზე. ანუ ყველა სურათს `Image` დირექტორიიდან იღებს, ამიტომ `dist/css`-ში გადატანა არ არის საჭირო.
