### ISSUE TITLE
სისტემის მესიჯების გასტილვა

### ISSUE THREAD

**Issue by otarza** [Girchi/girchi-com-d8#115]
# კონტექსტი
ამჟამად შეცდომა იქნაბა, ვალდიაციის შეცდომა თუ ნებისმიერი რამ, მესიჯი გამოდის გაუსტილავად, უბრალოდ ტექსტის სახით, საიტიზ ზედა ნაწილში გაუცენტრავად. 

# ტექნიკური დავალება
- [x] დიზაინში შესაბამისი კომპონენტის მოძებნა - ან თუ არ არის მოთხოვნა რომ ჩავამატოთ;
- [x] ამ კომპონენტის იმპლემენტაციის მოთხოვნის გაგზავნა @david-babunashvili - თან.
- [x] Drupal - ის თემაში შესაბამისი კომპონენტის ინტეგრაცია.

**Comment by otarza** [comment]
@ABGEO07 მზად არის ამის მარქაფი უკვე, გადმოვიტანე TODO - ში.

**Comment by ABGEO07** [comment]
> @ABGEO07 მზად არის ამის მარქაფი უკვე, გადმოვიტანე TODO - ში.

@otarza დამილინკე რა და მივხედავ დღეს.

**Comment by otarza** [comment]
@ABGEO07 როგორც @david-babunashvili - მა მითხრა შეგვიძლია პირდაპირ Bootstrap - ის მარქაფი გამოვიყენოთ: https://getbootstrap.com/docs/4.3/components/alerts/
