### ISSUE TITLE
კატეგორიების ბმულების UX - ის გაუმჯობესება და შესწორება

### ISSUE THREAD

**Issue by otarza** [Girchi/girchi-com-d8#141]
# კონტექსტი
ამჟამად საიდბარში parent კატეგორიებზე დაკლიკებისას ხდება მხოლოდ ჩაშლა და შესაბამისად პირდაპირ parent კატეგორიაზე ვერ შედიხარ.

მეორე პრობლემა რაც აღმოვაჩინე არის სიახლეების სიაში, teaser display - ში არსებული კატეგორიები გალინკულია term - ის გვერდზე და არა view - ს ფილტრზე. შესაბამისად იხსნება ესეთი გვერდი: https://girchi.com/ge/taxonomy/term/70

# ტექნიკური დავალება
- [x] Parent კატეგორიაზე დაკლიკებისას პირდაპირ უნდა იხსნებოდეს ეს კატეგორია;
- [x] Parent კატეგორიის მხოლოდ ისარზე დაკლიკებისას უნდა ხდებოდეს კატეგორიის ჩაშლა. თუ მარტივი ცვლილება არ არის მაშინ ამაში შეიძლება @david-babunashvili - ის დახმარება დაგვჭირდეს, შესაბამისად თუ საჭირო იქნა გაუხსენით შესაბამისი issue რეპოში: https://github.com/Girchi/girchi-com-ui 
- [x] თუ parent კატეგორიას დავაკლიკე და შესაბამისად გაფილტრულ გვერდზე აღმოვჩნდი მაშინ ეს კატეგორია უნდა გამოჩნდეს ჩაშლილად. 
- [x] სიახლის teaser display - ში კატეგორიის სწორად გალინკვა სიახლეების view - ზე შესაბამისი ფილტრით.

**Comment by IliaNoz** [comment]
- [ ] შიდა გვერდზე tag-ები არაა სწორად გალინკული.

**Comment by otarza** [comment]
@IliaNoz საიდბარში parent მენიუ ელემენტების გალინკული ვარიანტი უკვე დამერჯილია ფრონტზე და შეგიძლია გამოიყენო უკვე.

**Comment by otarza** [comment]
@IliaNoz ამ ტასკზე რას ვშვებით? ფრონტზე ყველაფერი მზადაა.
