### ISSUE TITLE
"მინდა პოლიტიკოსობა" ღილაკის იმპლემენტაცია

### ISSUE THREAD

**Issue by otarza** [Girchi/girchi-com-d8#146]
# კონტექსტი
მომხმარებლის პროფაილზე გვაქვს "მინდა პოლიტიკოსობა" ბლოკი შესაბამისი ღილაკით.

# ტექნიკური დავალება
- [x] ღილაკი უნდა ისქროლებოდეს "მინდა პოლიტიკოსობა" ბლოკზე;
- [x] თუ პროფაილის გვრდზე არ არის მომხმარებელი მაშინ ღილაკი უნდა ილინკებოდეს ამ გვერდზე და შემდეგ ისქროლებოდეს.

**Comment by thecotne** [comment]
"მინდა პოლიტიკოსობა" ბლოკში რა ხდება?

**Comment by otarza** [comment]
@thecotne უბრალოდ checkbox - ია რომელსაც ნიშნავს მომხმარებელი თუ პოლიტიკოსობა უნდა. შემდეგ არჩევნების დროს პარტიული სია შედგება იმ მომხმარებლებისგან ვინც მონიშნა ეს ჩეკბოქსი. სიაში ზემოთ იქნება ის ვისაც მეტი GeD + მეტი გირჩის წევრის მხარდაჭერა აქვს.

**Comment by otarza** [comment]
@chilaa ამის შესაბამისი PR არ ჩანს, მორჩენილია ამის იმპლემენტაცია?

**Comment by chilaa** [comment]
მოვრჩიი და #147 თასქი რო ჩაიმეჯრება მერე გასწორდება მაგაზეა დამოკიდებული, გავხსნი  ეხლა
