### ISSUE TITLE
საიტის კონფიგურირებადი გარემოს შექმნა

### ISSUE THREAD

**Issue by GGKapanadze** [Girchi/girchi-com-d8#156]
# კონტექსტი
 ადმინის მენიუში შევქმნათ გვერდი, საიდანაც საშუალება გვექნება ვმართოთ კონკრეტული კონფიგურაციები 

# ტექნიკური დავალება 
- [x] ჩავრთოთ მოდული **Omedia Site Settings** (`om_site_settings`)
- [x]  **SiteSettingsForm** - ში **buildForm** ფუნქციაში ვამატებთ კონფიგურირების ფორმებს 
 ![alt text](http://oi64.tinypic.com/2r4pkeg.jpg)   
   ##  ფორმის მაგალითი 

```php
     $form['social_media'] = [
            '#type' => 'details',
            '#open' => true,
            '#title' => 'Social Media',
        ];
     $form['social_media']['social_media_facebook'] = [
            '#description' => "Enter your facebook page url",
            '#type' => 'textfield',
            '#title' => 'Facebook page url',
            '#default_value' => $config->get('social_media_facebook'),
        ];
     $form['social_media']['social_media_twitter'] = [
            '#description' => "Enter your twitter page url",
            '#type' => 'textfield',
            '#title' => 'Twitter profile url',
            '#default_value' => $config->get('social_media_twitter'),
        ];
```
- [x] ფორმის შექმნის შემდეგ ფორმის კონფიგების შესაქმნელად `$fields` მასივში ვამატებთ სასურველ კონფიგებს 

 ```php
   $fields = [
            'social_media_facebook',
            'social_media_twitter'
        ];
````
*  `http://girchi.docker.localhost/en/admin/config/site-settings`  ამ მისამართზე მივიღებთ ფორმას

 ![alt text](http://oi67.tinypic.com/14azia9.jpg)   
 
* სასრუველი კოფნიგის ამოსაღებად ვიქცევით შემდეგნაირად 
```php
  $config = \Drupal::config('om_site_settings.site_settings');
  $config->get('social_media_facebook')
```

**Comment by IliaNoz** [comment]
გამარტივებულია ეს ბევრად. `om_site_settings.schema.yml` ამ ფაილში წერ უბრალოდ 
![image](https://user-images.githubusercontent.com/17799522/58276521-b66bb300-7da8-11e9-8789-a07f147a819e.png)
ესეთი სახით და თავისით აგენერირებს ფორმას.

SiteSettingsForm.php-ში ნახე buildForm ფუნქცია.

**Comment by GGKapanadze** [comment]
ეხლა ისეა მოწყობილი კოფიგების დასეტვა რო ეგ მიდგომა არ იმუშავებს, თან კონფიგების ლოგიკურად დაჯგუფებაში და აღწერის გასაკეთებლად ადმინისტრატორისთვის ის მიდგომა ჯობია.
