### ISSUE TITLE
ძებნის ფუნქციონალის იმპლემენტაცია

### ISSUE THREAD

**Issue by otarza** [Girchi/girchi-com-d8#157]
# კონტექსტი
საიტზე გვჭირდება ძებნის ფუნქციონალი. ფრონტი მზად არის, search-bar გვაქვს. 

# ტექნიკური დავალება
- [x] მოკვლევა როგორ ჯობია search - ის გაკეთება, საჭიროების შემთხვევაში @ggagosh  - სთან კონსულტაციის გავლა
- [x] search bar - ის ამუშავება;
- [x] სერჩის შედეგების გამოტანა იგივე ფორმატით როგორიცაა სიახლეების გრიდი.

**Comment by jibla** [comment]
მოკლედ ჩამოვწერ, სრაფად რა არის გასაკეთებელი ამ თასზე:
