### ISSUE TITLE
მთლიანი პარტიული სიის გენერირება

### ISSUE THREAD

**Issue by IliaNoz** [Girchi/girchi-com-d8#176]
# კონტექსტი
გვჭირდება პარტიული სია

## ტექნიკური დავალება
- [x] მომხმარებლის პროფილში უნდა შეინახოს პარტიული სიის მიხედვით მერამდენეა, ველში `field_place_in_parliamentary_list`
- [x] უნდა შეიქმნას საერთო პარტიული სიის view

**Comment by jibla** [comment]
პარტიული სიის view ცალკე თასქი უნდა იყოს imho, იმიტომ რომ სრულიად დამოუკიდბელად შეიძლება მუშაობა მაგაზე. გავხსნი თასქს. @otarza ამის დიზაინი გვაქვს?
