### ISSUE TITLE
კონტენტის დუბლირების პრობლემა

### ISSUE THREAD

**Issue by GGKapanadze** [Girchi/girchi-com-d8#182]
## კონტექსტი 
მოცემულ მომენტში News view-ში (`/news`) მეორდება კონტენტი არჩეული  თაგების რაოდენობის მიხედვით 

## ტექტიკური დავალება
გადავამოწმოთ ფილტრები, მოვძებნოთ პრობლემა და მოვაგვაროთ

**Comment by jibla** [comment]
ამის სოლუშენი:
- [ ] დაარედაქტირეთ view - `/admin/structure/views/view/news`
- [ ] ჩაურთეთ აგრეგაცია `Use aggregation`-დან (Advanced-ში)
- [ ] ჩაურთეთ Distinct, `Query settings`-დან
- [ ] დააექსპორტეთ კონფიგურაცია და დააკომიტეთ.

იხილეთ სქრინები:
![image](https://user-images.githubusercontent.com/475343/58457493-e95ecf80-8137-11e9-95ae-232cc6ad0698.png)

![image](https://user-images.githubusercontent.com/475343/58457466-d5b36900-8137-11e9-8f42-c06687483da0.png)

![image](https://user-images.githubusercontent.com/475343/58457517-f7145500-8137-11e9-91a7-06b2d0b1680f.png)
