### ISSUE TITLE
Staging - სერვერის მომზადება Wodby Cloud - ზე ავტომატური დეპლოიმენტით 

### ISSUE THREAD

**Issue by otarza** [Girchi/girchi-com-d8#2]
- [ ] გირჩის ექაუნთის რეგისტრაცია [DigitalOcean](https://www.digitalocean.com/) - ზე;
- [ ] გირჩის ექაუნთის რეგისტრაცია [Wodby](https://www.digitalocean.com/) - ზე;
- [ ] ავტომატური დეფლოიმენთის კონფიგურირება Wodby - ზე dev - ბრენჩზე დამერჟილი კოდისთვის;

**Comment by jibla** [comment]
ამას ვხურავ, რადგან ჯენკინსით და ომედიას VPS-ზე იგივე შედეგი გვაქვს უკვე.
