### ISSUE TITLE
ტაქსონომიების სიის გვერდი არ მუშაობს ფროდაქშენზე

### ISSUE THREAD

**Issue by otarza** [Girchi/girchi-com-d8#202]
# კონტექსტი
ფროდაქშენზე `/admin/structure/taxonomy/manage/news_categories/overview` - ამ გვერდზე შესვლისას გვაქვს შეცდომა: 
```Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS expression FROM tfr INNER JOIN tr ON tfr. = tr. AND tr. = 0 INNER JOIN (S' at line 1: SELECT tfr.tid AS tid, MAX(tfr.) AS expression FROM {} tfr INNER JOIN {} tr ON tfr. = tr. AND tr. = 0 INNER JOIN (SELECT t.tid AS tid, t.langcode AS langcode, MAX(t.) AS expression FROM {} t WHERE t. = :db_condition_placeholder_0 GROUP BY t.tid, t.langcode) mr ON tfr. = mr. AND tfr.langcode = mr.langcode GROUP BY tfr.tid; Array ( [:db_condition_placeholder_0] => 1 ) in Drupal\taxonomy\TermStorage->getTermIdsWithPendingRevisions() (line 404 of /var/www/girchi/html/web/core/modules/taxonomy/src/TermStorage.php).```

# ტექნიკური დავალება
- [ ] პრობლემის იდენტიფიციერბა და გასწორება.

**Comment by jibla** [comment]
ვხურავ. ბაზის განახლება იყო საჭირო პროდაქშენზე და @ggagosh ამ გააკეთა.
