### ISSUE TITLE
ტელეფონის ველის გაუმჯობესება

### ISSUE THREAD

**Issue by otarza** [Girchi/girchi-com-d8#333]
# კონტექსტი
მომხმარებლების რეგისტრაციისას გამოიკვეთა 2 პრობლემა:
1. მომხმარებლებს სურთ რომ შეეძლოთ რეგისტრაცია არაქართული ნომრებიდანაც იმიტომ რომ საკმაო რაოდენობის გირჩელი აღმოჩნდა საზღვარგარეთ. 
2. მომხმარებლებისთვის დამაბნეველია ქვეყნის კოდის მითითების აუცილებლობა, +995 - ის გარეშე წერენ და ფორმატის შეცდომაზე გადიან.

## ტექნიკური დავალება
- [x] მომხმარებლებს უნდა შეეძლოთ ნებისმიერი ქვეყნსი ნომრის ჩაწერა.
- [x] ტელეფონის ნომრის ველის წინ უნდა იყოს ქვეყნის არჩევის drop-down ველი, სადაც გამოჩნდება როგორც ქვეყნის კოდი, ასევე დროშა, აი ამ ვიჯეტის მსგავსად: https://intl-tel-input.com/ - პირდაპირ ამ ვიჯეტის ინტეგრაციაც შეიძლება ალბათ, ან შეიძლება Drupal - შივე იყოს ამის გაკეთების საშუალება, დასარესერჩებელია.
- [x] ტელეფონის ველში by default - საქართველოს კოდი უნდა იყოს არჩეული. 

UI: თუ ამ ტასკისთვის შესაბამისი მარქაფი არ გვაქვს ან დაჭირდა გასტილვა შეგიძლიათ გახსნათ Issue girchi-com-ui რეპოში და @david-babunashvili - ს ვთხოვოთ დახმარება, ან თუ მარტივია ჩვენით გავსტილოთ და PR - გავაგზავნოთ მაგ რეპოში.

**Comment by otarza** [comment]
@glontianano ეს ტასკი დასრულდა?

**Comment by glontianano** [comment]
@otarza https://github.com/Girchi/girchi-com-ui/issues/83 ეს issue გავუხსენი დავითს 4 ივლისს და ველოდებოდი ui-ში მაგის დამერჯვას. მაგრამ მგონი ჯობია ჩვენით გავაკეთოთ და დავითს აღარ დაველოდოთ.

**Comment by david-babunashvili** [comment]
@glontianano https://github.com/Girchi/girchi-com-ui/blob/develop/src/settings.html#L323

**Comment by david-babunashvili** [comment]
ეგ issue იყო როგორც მახსოვს რომ UI არ გვქონდა ვალიდაციის ნომრების ფილდზე

**Comment by david-babunashvili** [comment]
სლექში მოვიწერე მახსოვს და მოგთაგე მაგაზე
