### ISSUE TITLE
პარტიული სიის გვერდის ხარვეზები

### ISSUE THREAD

**Issue by david-babunashvili** [Girchi/girchi-com-d8#340]
- [ ] http://prntscr.com/o98f5c html არასწორად არის დაგენერირებული რაც ურევს ლისტის სტილებს 
- [ ] http://prntscr.com/o98ggh ნუმერაციას მგონი რაღაც ჭირს

**Comment by otarza** [comment]
ამის რედიზაინი გავაკეთეთ.
