### ISSUE TITLE
ჩემ პარტიულ სიაში პროცენტების მნიშვნელობის ვალიდაცია არასწორად ხდება

### ISSUE THREAD

**Issue by jgerenaial** [Girchi/girchi-com-d8#366]
ჩემს პარტიულ სიაში მობილურით რო შედიხარ მხადრასაჭერა, ნულიანი რჩება ციფრების წინ.

დაახლოებით მსგავსად არის დესკტოპის ვერსიაზეც, უნდა მონიშნო ან ხელით წაშალო დეფოლტად ნული რო წერია ეგ.
![xmis micema](https://user-images.githubusercontent.com/50403920/61286580-3411d500-a7d4-11e9-87c5-1fffb2ad9011.jpg)

**Comment by david-babunashvili** [comment]
ეს ცოტა საკამათო თემაა როგორც ჩანს ბაზაში 0 არი შენახული და 0-ს ადგილას რომ სხვა რიცხვი ეწეროს მაინც წაშლა და თავიდან ჩაწერა მოგიწევს და იგივე სიტუაციაა აქაც. რავი თუ გინდათ დავადებ მაგ შეზღუდვას რომ 0ით დაწყებულ რიცხვებს წინ 0 წაუშალოს.

**Comment by david-babunashvili** [comment]
@otarza
