### ISSUE TITLE
Facebook რეგისტრაცია/ავტორიზაცია

### ISSUE THREAD

**Issue by otarza** [Girchi/girchi-com-d8#5]
- [ ] [simple_fb_connect](https://www.drupal.org/project/simple_fb_connect) - მოდულის ინსტალაცია;

ინსტალაციის და კონფიგურაციის ინსტრუქციები: https://www.drupal.org/docs/8/modules/simple-fb-connect-8x

**Comment by jibla** [comment]
@glontianano შევხედე ბრენჩს, გავმარმთე, ყველაფერ იდეაში მზადაა იმისთვის რომ სტეიჯინგზე დაიტესტოს. კარგია. ვნახოთ რო გაიმართება სერვერი.

ერთადერთი, fb auth ღილაკი ჰედერიდან წამოიღე დაContent რეგიონში ჩასვი და მერე theming-ზე რომ გადავალთ შეიძლება ფორმაშიც ჩავსვათ.

**Comment by jibla** [comment]
ვხურავ ამას. საბოლოოდ social auth-ით გაკეთდა (მომავალში ნებისმიერი სორსის დამატების საშუალებით).
