### ISSUE TITLE
UI-სთვის Docker კონტეინერის მომზადება

### ISSUE THREAD

**Issue by ABGEO07** [Girchi/girchi-com-d8#56]
# კონტექსტი
გვჭირდება ახალი დოკერ კონტეინერის მომზადება, სადაც გაიბილდება UI სტილები და სკრიპტები https://github.com/Girchi/girchi-com-ui - დან.

# ტექნიკური დავალება
- [x] ახალი კონტეინერის მომზადება ინსტალირებული `node`, `npm` და `yarn`-ით.

**Comment by thecotne** [comment]
node ის ოფიციალურ image ში არის ყველაფერი რაც ფრონტს ჭირდება (custom image არ ჭრდება ანუ)

> All of the images contain pre-installed versions of node, npm, and yarn
https://github.com/nodejs/docker-node#image-variants

**Comment by otarza** [comment]
@thecotne ცალკე იმიჯს არ ვამზადებთ, docker4drupal სტეკს ვიყენებთ და მანდ გვაქვს უკვე მომზადებული ნოუდი, პირდაპირ ამას მივიერთებთ: https://github.com/Girchi/girchi-com-d8/blob/dev/docker-compose.yml#L203

**Comment by thecotne** [comment]
@otarza cool 👍

სათაურიდან ისეთი შთაბეჭდილება დამრჩა რომ custom image ის აწყობას აპირებდით ...
