### ISSUE TITLE
Direct Debit-ის რედაქტირების შეცდომა

### ISSUE THREAD

**Issue by amikelashvili** [Girchi/girchi-com-d8#623]
ავტომატური დაფინანსების მართვის ფეიჯზე ჩანაწერის "რედაქტირებაზე" კლიკისას შეცდომას აბრუნებს

[https://www.girchi.com/ge/user/regular-donations/list](url)

![Capture](https://user-images.githubusercontent.com/52528077/72635015-40d6d780-3975-11ea-9e18-6337b7aef448.PNG)

**Comment by ABGEO07** [comment]
მადლობა, გაფიქსულია.
