### ISSUE TITLE
ყოველთვიური გადახდების ბაგი

### ISSUE THREAD

**Issue by bakurits** [Girchi/girchi-com-d8#657]
![Screenshot from 2020-02-07 12-41-34](https://user-images.githubusercontent.com/10448754/74014079-5739e700-49a7-11ea-8bd4-854ee8a0e1f5.png)

მიმაგრებული მაქ ყოველთვიური გადახდები მაგრამ მგონი აღარ მუშაობს. 3 თებერვალს მიწერს შემდეგ გადახდას და 7 ია ახლა. ტრანზაქციების ისტორიაში ბოლოს 03.12.19 გადავიხადე 
იუზერ ID 102

**Comment by GGKapanadze** [comment]
დღევანდელი განახლების მერე უნდა გასწორებულიყო
