### ISSUE TITLE
მთავარი კონტენტის რეგიონისთვის მარჯინები

### ISSUE THREAD

**Issue by jibla** [Girchi/girchi-com-d8#76]
# კონტექსტი
margin-ები არის გასასწორებელი main content რეგიონსა და ჰედერს და ფუტერს შორის.

**ჩვენთან:**
ჰედერიდან:
![image](https://user-images.githubusercontent.com/475343/56793811-dc3f7f80-681d-11e9-8e21-6287ef2590e3.png)

ფუტერამდე:
![image](https://user-images.githubusercontent.com/475343/56793825-e792ab00-681d-11e9-86fb-6d787b2e018d.png)

**მარქაფში:**
ჰედერიდან:
![image](https://user-images.githubusercontent.com/475343/56793786-d184ea80-681d-11e9-80ac-dcaaeefa3a6d.png)

ფუტერამდე:
![image](https://user-images.githubusercontent.com/475343/56793772-ca5ddc80-681d-11e9-92e7-ac65fe7fb235.png)

# ტექნიკური დავალება

უბრალოდ გადაამოწმეთ რამდენად ემთხვევა layout, მარქაფისას. შეიძლება სადმე ვრაპერი გაკლიათ ან კლასი.

**Comment by glontianano** [comment]
გასწორებულია უკვე

**Comment by otarza** [comment]
@glontianano არ არის ესენი გასწორებული, მაგალითად სიახლეების გვერდი რომ დავამატეთ იქაც იგივე პრობლემაა, ისე უნდა მოვაგვაროთ რომ ახალ გვერდებზე სათითაოდ ცალკე კეთება არ დაგვჭირდეს.
