### ISSUE TITLE
არჩევნების გვერძე პროგრესის არასწორია

### ISSUE THREAD

**Issue by giorgi-peranidze** [Girchi/girchi-com-d8#775]
პროგრესის ბარი არ შეესაბამება რეალობას, 87.698% უნდა იყოს 63.096% ნაცვლად.

<img width="1189" alt="Screenshot 2020-08-28 at 11 48 30" src="https://user-images.githubusercontent.com/53253671/91541092-763c9e00-e924-11ea-8a59-b03fc175d42a.png">

[ეს ფორმულა](https://github.com/Girchi/girchi-com-d8/blob/07674dd7ba050ea24bf939a7720c95f43459e1a1/web/themes/custom/girchi/templates/pages/page-election-2020.html.twig#L233) არასწორია, უკეთესი იქნებოდა 
`milestones.milestoneStart * 100 / total_amount`

**Comment by jibla** [comment]
@IliaNoz  რაღაც მოთხოვნა იყო რომ მაგ პროგრეს ბარს სხვანაირად ეჩვენებინა როგორც მახსოვს :)) მარა შეხედე რა ორშაბათს ამ იშუს.

@giorgi-peranidze დიდი მადლობა.

**Comment by IliaNoz** [comment]
@jibla პროგრეს ბარი ასახავს milestone-ის პროგერსს, რომელიც 25 000 ლარია. შესაბამისად ყოველი მაილსთოუნის შესრულების შემდეგ პროგრეს ბარი და მაილსთოუნი რესეტდება, მიზანი 25 000 ლარით იმატებს. 

@giorgi-peranidze   მადლობა.
